import type { AppSettings, BenchPreset } from "./types";

export const DEFAULT_PROMPTS = {
  short:
    "日本語で短く答えてください。ローカルLLMをApple Siliconで動かす利点を3つ挙げてください。",
  long:
    "日本語で、ローカルLLMをApple Silicon上で運用するときの速度、メモリ、コンテキスト長、量子化、推論サーバー選定の観点を、実務向けに詳しく説明してください。",
};

export const DEFAULT_SETTINGS: AppSettings = {
  ollamaUrl: "http://127.0.0.1:11434",
  mlxUrl: "http://127.0.0.1:18080",
  mlxModel:
    "/Users/admin/Prj/local-llm-bench-lab/experiments/gemma4-2026-04-29/full-copy/models/mlx-community-gemma-4-e2b-it-4bit",
  llamaBenchPath: "",
  llamaHf: "ggml-org/gemma-4-E4B-it-GGUF:Q4_K_M",
  nGpuLayers: 99,
  flashAttention: true,
};

export const PRESETS: BenchPreset[] = [
  {
    id: "mlx-e2b-server",
    backend: "mlx_server",
    title: "Gemma 4 E2B / MLX server",
    model: "E2B 4bit",
    target: "mlx-vlm 0.4.4 + KV 8bit uniform",
    expectedGenerationTps: 70.8,
    expectedPromptTps: 355,
    expectedMemoryGb: 3.74,
    expectedLatency: "短文 約1秒",
    maxTokens: 512,
    note: "常駐サーバーで体感が軽い設定",
    tags: ["最速候補", "低メモリ", "server"],
  },
  {
    id: "ollama-e2b",
    backend: "ollama",
    title: "gemma4:e2b / Ollama",
    model: "gemma4:e2b",
    target: "Q4_K_M, keep_alive 30m 想定",
    expectedGenerationTps: 70.1,
    expectedPromptTps: 584,
    expectedMemoryGb: 7.7,
    expectedLatency: "cold 約4.3秒",
    maxTokens: 512,
    numCtx: 4096,
    note: "Ollama 内では最速",
    tags: ["Ollama", "軽量"],
  },
  {
    id: "ollama-e4b",
    backend: "ollama",
    title: "gemma4:e4b / Ollama",
    model: "gemma4:e4b",
    target: "Q4_K_M, 標準利用",
    expectedGenerationTps: 36.2,
    expectedPromptTps: 348,
    expectedMemoryGb: 10,
    expectedLatency: "約2-4秒",
    maxTokens: 512,
    numCtx: 4096,
    note: "軽めのバランス型",
    tags: ["Ollama", "標準"],
  },
  {
    id: "ollama-26b",
    backend: "ollama",
    title: "gemma4:26b / Ollama",
    model: "gemma4:26b",
    target: "Q4_K_M, Sparse MoE",
    expectedGenerationTps: 36.2,
    expectedPromptTps: 262,
    expectedMemoryGb: 19,
    expectedLatency: "cold 約7.1秒",
    maxTokens: 512,
    numCtx: 4096,
    note: "品質寄りでまだ実用速度",
    tags: ["Ollama", "品質寄り"],
    heavy: true,
  },
  {
    id: "ollama-31b",
    backend: "ollama",
    title: "gemma4:31b / Ollama",
    model: "gemma4:31b",
    target: "Q4_K_M, dense",
    expectedGenerationTps: 9.14,
    expectedPromptTps: 71,
    expectedMemoryGb: 25,
    expectedLatency: "cold 約14.8秒",
    maxTokens: 512,
    numCtx: 4096,
    note: "品質確認用。体感はかなり重い",
    tags: ["Ollama", "重量級"],
    heavy: true,
  },
  {
    id: "llamacpp-e4b",
    backend: "llamacpp",
    title: "Gemma 4 E4B / llama.cpp",
    model: "E4B GGUF Q4_K_M",
    target: "Metal + -ngl 99 + -fa 1",
    expectedGenerationTps: 38.5,
    expectedPromptTps: 537.9,
    maxTokens: 512,
    llamaPromptTokens: 512,
    llamaHf: "ggml-org/gemma-4-E4B-it-GGUF:Q4_K_M",
    flashAttention: true,
    nGpuLayers: 99,
    note: "llama-bench で速度測定",
    tags: ["llama.cpp", "GGUF"],
  },
];

export const LIGHT_PRESET_IDS = ["mlx-e2b-server", "ollama-e2b", "llamacpp-e4b"];
